"""
Reads pwa/index.html and writes api_webapp.cpp with the content embedded
as a C string literal, compatible with ESPAsyncWebServer.
"""
import os, sys

src  = os.path.join(os.path.dirname(__file__), 'pwa', 'index.html')
dest = os.path.join(os.path.dirname(__file__), 'api_webapp.cpp')

with open(src, 'r', encoding='utf-8') as f:
    html = f.read()

def escape(s):
    return (s.replace('\\', '\\\\')
             .replace('"',  '\\"')
             .replace('\r\n', '\\n"\n    "')
             .replace('\n',   '\\n"\n    "'))

escaped = escape(html)

out = f'''#include "config.h"
#include "api_server.h"
#include "api_webapp.h"

// Auto-generated by embed_pwa.py — do not edit by hand.
// Edit pwa/index.html then run embed-pwa.bat.

static const char INDEX_HTML[] PROGMEM =
    "{escaped}";

void setupWebApp() {{
    apiServer.http().on("/", HTTP_GET, [](AsyncWebServerRequest* req) {{
        AsyncWebServerResponse* resp = req->beginResponse_P(200, "text/html", INDEX_HTML);
        resp->addHeader("Cache-Control", "no-cache");
        req->send(resp);
    }});
    Serial.println("[API] Web app registered at /");
}}
'''

with open(dest, 'w', encoding='utf-8') as f:
    f.write(out)

print(f"Embedded {len(html):,} bytes -> {dest}")
